---
title: "Analyse Wassertiefen"
format: html
editor: visual
---

# 1 Genutzte Packages

```{r}
library(readxl)
library(dplyr)
library(ggplot2)
library(tidyr)
```

# 2 Daten einlesen

```{r}
chemie <- read_excel("3 Auswertung Photometrie.xlsx", sheet = 5)
summary(chemie)
str(chemie)
class(chemie$Datum)

# Datum als Date konvertieren
chemie$Datum <- as.Date(chemie$Datum)
str(chemie)
class(chemie$Datum)

# Spalten von chr in num umwandeln 
chemie <- chemie %>%
  mutate(
    Ammonium = as.numeric(Ammonium),
    Phosphat = as.numeric(Phosphat),
    Nitrat = as.numeric(Nitrat)
  )
str(chemie)

```

## Long-Format erzeugen

```{r}
chemie_long <- chemie %>%
  pivot_longer(cols = c(Ammonium, Phosphat, Nitrat),
               names_to = "Parameter",
               values_to = "Wert")
```

# 3 Auswertung

```{r}
# Statistik je Messpunkt und Parameter
chemie_stats_messpunkt <- chemie_long %>%
  group_by(ID, Parameter) %>%
  summarise(
    mean = mean(Wert, na.rm = TRUE),
    sd = sd(Wert, na.rm = TRUE),
    median = median(Wert, na.rm = TRUE),
    min = min(Wert, na.rm = TRUE),
    max = max(Wert, na.rm = TRUE),
    range = max - min,
    .groups = "drop"
  )

chemie_stats_messpunkt
```

```{r}
# Statistik je Standort und Parameter
chemie_stats_flaeche <- chemie_long %>%
  group_by(Standort, Parameter) %>%
  summarise(
    mean = mean(Wert, na.rm = TRUE),
    sd = sd(Wert, na.rm = TRUE),
    median = median(Wert, na.rm = TRUE),
    min = min(Wert, na.rm = TRUE),
    max = max(Wert, na.rm = TRUE),
    range = max - min,
    .groups = "drop"
  )

chemie_stats_flaeche
```

## Diagramme

nur so zum ausprobieren, ich benötige keine zum Weiterarbeiten

```{r}

ggplot(chemie, aes(x = Datum, y = Nitrat, color = ID, group = ID)) +
  geom_line() +
  geom_point(size = 2) +
  labs(
    title = "Nitrat-Verlauf je Logger",
    x = "Datum",
    y = "Nitrat [mg/L]"
  ) +
  theme_minimal()
```

```{r}
chemie_standort <- chemie %>%
  group_by(Datum, Standort) %>%
  summarise(
    Nitrat = mean(Nitrat, na.rm = TRUE),
    .groups = "drop"
  )

ggplot(chemie_standort,
       aes(x = Datum, y = Nitrat,
           color = Standort,
           group = Standort)) +
  geom_line(size = 1.2) +
  geom_point(size = 3) +
  labs(
    title = "Mittlerer Nitrat-Verlauf je Standort",
    x = "Datum",
    y = "Nitrat [mg/L]"
  ) +
  theme_minimal()
```
