---
title: "Analyse Wasserchemie"
format: html
editor: visual
---

# 1 Genutzte Packages

```{r}
library(readxl) 
library(dplyr) 
library(ggplot2) 
#library(lubridate) 
#library(tidyr)
```

# 2 Daten einlesen

```{r}
WS <- read_excel("Chemische Parameter_Tabelle.xlsx")
summary(WS) 
str(WS) 
class(WS$Datum)  

# Datum als Date konvertieren 
WS$Datum <- as.Date(WS$Datum) 
str(WS) 
class(WS$Datum)  

# Spalten von chr in num umwandeln  
WS <- WS %>%
  mutate(
    Messstelle = as.numeric(Messstelle),
    Messwert = as.numeric(Messwert),
    Temperatur = as.numeric(Temperatur)
    ) 

str(WS) 
```

# 3 Auswertung

```{r}
# Statistiken je Messpunkt und Parameter
WS_stats_Messpunkte <- WS %>%
  group_by(ID, Parameter) %>%
  summarise(
    Mean = mean(Messwert, na.rm = TRUE),
    Median = median(Messwert, na.rm = TRUE),
    SD = sd(Messwert, na.rm = TRUE),
    Min = min(Messwert, na.rm = TRUE),
    Max = max(Messwert, na.rm = TRUE),
    Range = Max - Min,
    .groups = "drop"
  )

WS_stats_Messpunkte
```

```{r}
# Statistiken je Fläche und Parameter
WS_stats_Flaeche <- WS %>%
  group_by(Fläche, Parameter) %>%
  summarise(
    Mean = mean(Messwert, na.rm = TRUE),
    Median = median(Messwert, na.rm = TRUE),
    SD = sd(Messwert, na.rm = TRUE),
    Min = min(Messwert, na.rm = TRUE),
    Max = max(Messwert, na.rm = TRUE),
    Range = Max - Min,
    .groups = "drop"
  )

WS_stats_Flaeche
```

## Ohne Messstelle 4 bei Lichtenau

```{r}
# Statistiken je Messpunkt und Parameter
WS_stats_Messpunkte_L <- WS %>%
  filter(ID != "L4") %>%
  group_by(ID, Parameter) %>%
  summarise(
    Mean = mean(Messwert, na.rm = TRUE),
    Median = median(Messwert, na.rm = TRUE),
    SD = sd(Messwert, na.rm = TRUE),
    Min = min(Messwert, na.rm = TRUE),
    Max = max(Messwert, na.rm = TRUE),
    Range = Max - Min,
    .groups = "drop"
  )

WS_stats_Messpunkte_L
```

```{r}
# Statistiken je Fläche und Parameter
WS_stats_Flaeche_L <- WS %>%
  filter(ID != "L4") %>%
  group_by(Fläche, Parameter) %>%
  summarise(
    Mean = mean(Messwert, na.rm = TRUE),
    Median = median(Messwert, na.rm = TRUE),
    SD = sd(Messwert, na.rm = TRUE),
    Min = min(Messwert, na.rm = TRUE),
    Max = max(Messwert, na.rm = TRUE),
    Range = Max - Min,
    .groups = "drop"
  )

WS_stats_Flaeche_L
```

## Diagramme 

nur so zum ausprobieren, ich benötige keine zum Weiterarbeiten

```{r}
# Mittelwerte je Fläche und Datum 
WS_mean_flaeche <- WS %>%
  group_by(Datum, Fläche, Parameter) %>%
  summarise(
    Mean_Messwert = mean(Messwert, na.rm = TRUE),
    .groups = "drop"
  )
```

```{r}
WS_mean_flaeche %>%
  filter(Parameter == "Sauerstoffgehalt (mg/l)") %>%
  ggplot(aes(x = Datum, y = Mean_Messwert, color = Fläche)) +
  geom_line(linewidth = 1) +
  geom_point(size = 2) +
  labs(
    title = "pH-Verlauf je Fläche (gemittelt über Messpunkte)",
    x = "Datum",
    y = "pH",
    color = "Fläche"
  ) +
  theme_minimal()
```
