---
title: "Analyse Wassertiefen"
format: html
editor: visual
---

# 1 Genutzte Packages

```{r}
#| output: false
library(readxl)
library(dplyr)
library(ggplot2)
library(lubridate)
library(tidyr)
```

# 2 Daten einlesen

```{r}
Wassertiefen <- read_excel("Tabelle Wassertiefe.xlsx")
summary(Wassertiefen)
str(Wassertiefen)
class(Wassertiefen$Datum)

# Datum als Date konvertieren
Wassertiefen$Datum <- as.Date(Wassertiefen$Datum)

str(Wassertiefen)
class(Wassertiefen$Datum)
```

# 3 Auswertung

## 3.1 Statistische Kennzahlen

```{r}
# Statistische Kennzahlen pro Messpunkt und Standort
Kennzahlen_messpunkt <- Wassertiefen %>%
  group_by(Standort, Messpunkt) %>%
  summarise(
    Mittelwert = mean(Wassertiefe, na.rm = TRUE),
    Median = median(Wassertiefe, na.rm = TRUE),
    Std = sd(Wassertiefe, na.rm = TRUE),
    Min = min(Wassertiefe, na.rm = TRUE),
    Max = max(Wassertiefe, na.rm = TRUE),
    Range = max(Wassertiefe, na.rm = TRUE) - min(Wassertiefe, na.rm = TRUE),
  )

Kennzahlen_messpunkt
```

```{r}
# Statistische Kennzahlen pro Standort
Kennzahlen_standort <- Wassertiefen %>%
  #filter(ID != "L4") %>%
  group_by(Standort) %>%
  summarise(
    Mittelwert = mean(Wassertiefe, na.rm = TRUE),
    Median = median(Wassertiefe, na.rm = TRUE),
    Std = sd(Wassertiefe, na.rm = TRUE),
    Min = min(Wassertiefe, na.rm = TRUE),
    Max = max(Wassertiefe, na.rm = TRUE),
    Range = max(Wassertiefe, na.rm = TRUE) - min(Wassertiefe, na.rm = TRUE)
  )

Kennzahlen_standort
```

#### 3.1.1 Wasserstandsschwankungen

```{r}
# Mittelwerte pro Tag/ pro Standort berechnen 
WT_mittel <- Wassertiefen %>% 
  group_by(Datum, Standort) %>% 
  summarise(WT_mean = mean(Wassertiefe, na.rm = TRUE)) %>% 
  ungroup()
```

```{r}
# welcher Standort hat die größten Wasserstandsschwankungen?

# Standardabweichung = wie stark der Wasserstand typischerweise um seinen Mittelwert schwankt
# Spannweite des Wasserstands = extremste Unterschiede zwischen dem höchsten und niedrigsten gemessenen Wasserstand
# für die einzelnen Messpunkte auch aus den Kennzahlen_messpunkt ersichtlich

#Schwankung pro Standort (über Tagesmittelwerte)
WT_var_st <- WT_mittel %>%
  group_by(Standort) %>%
  summarise(
    sd_WT = sd(WT_mean, na.rm = TRUE),
    range_WT = max(WT_mean, na.rm = TRUE) - min(WT_mean, na.rm = TRUE)
  ) %>%
  arrange(desc(sd_WT))

WT_var_st
```

#### 3.1.2 Häufigkeit der Wasserstände

```{r}
# welcher Standort hat die meisten trocken gefallenen Tage, welcher die wenigsten (= Beständigkeit des Gewässers/Wasserspiegel)

WT_trocken_mp <- Wassertiefen %>%
  group_by(Standort, Messpunkt) %>%
  summarise(
    trockene_Tage = sum(Wassertiefe <= 1, na.rm = TRUE),
    gesamt_Messungen = n(),
    anteil_trocken = trockene_Tage / gesamt_Messungen
  ) %>%
  arrange(Standort, desc(trockene_Tage))

WT_trocken_mp

```

```{r}
# Histogramm zur Häufigkeit der Wasserstände je Standort 
ggplot(Wassertiefen, aes(x = Wassertiefe, fill = Standort)) +
  geom_histogram(binwidth = 5, alpha = 0.7) +
  facet_wrap(~Standort) +
  theme_minimal() +
  labs(title = "Verteilung der Wasserstände pro Standort",
       x = "Wasserstand (cm)",
       y = "Anzahl der Messungen")

# Histogramm zur Häufigkeit der Wasserstände je Standort ohne Messpunkt 4 bei Lihtenau 
ggplot(
  Wassertiefen %>%
    filter(!(Standort == "L" & Messpunkt == 4)) %>%
    mutate(Standort = factor(Standort, levels = c("MT", "MN", "L"))),
  aes(x = Wassertiefe, fill = Standort)
) +
  geom_histogram(binwidth = 5, alpha = 0.7) +
  facet_wrap(~Standort) +
  labs(
    title = "",
    x = "Wasserstand (cm)",
    y = "Anzahl der Messungen",
    fill = "Fläche"              
  ) +
  scale_fill_manual(
    values = c(
      "MT" = "#D55E00",
      "MN" = "#6495ED",
      "L"  = "#006400"
    ),
    labels = c(                  
      "MT" = "1",
      "MN" = "2",
      "L"  = "3"
    )
  ) +
  theme(
    axis.title.x = element_text(size = 16),
    axis.title.y = element_text(size = 16),
    
    axis.text.x = element_text(size = 14),
    axis.text.y = element_text(size = 14),
    
    legend.title = element_text(size = 15),
    legend.text = element_text(size = 14),
    
    panel.grid.major = element_line(color = "grey75"),
    panel.grid.minor = element_line(color = "grey85"),
    
    axis.ticks = element_blank(),
    
    panel.background = element_rect(fill = "white", color = NA),
    
    strip.background = element_blank(),  # graue Balken entfernen
    strip.text = element_blank()         # MT/MN/L entfernen
  )
```

```{r}
# Histogramm zur Häufigkeit der Wasserstände je Messpunkt und Standort 
Wassertiefen$Standort <- as.factor(Wassertiefen$Standort)
Wassertiefen$Messpunkt <- as.factor(Wassertiefen$Messpunkt)

standort_L <- Wassertiefen %>% 
  filter(Standort == "L")
standort_L <- Wassertiefen %>%
  filter(Standort == "L", Messpunkt != "4")#ohne Messpunkt 4 (verzerrt Daten)
standort_MN <- Wassertiefen %>% 
  filter(Standort == "MN")
standort_MT <- Wassertiefen %>% 
  filter(Standort == "MT")

ggplot(standort_MT, aes(x = Wassertiefe, fill = factor(Messpunkt))) +
  geom_histogram(binwidth = 5, alpha = 0.7) +
  facet_wrap(~Messpunkt) +
  labs(
    title = "",
    x = "Wasserstand (cm)",
    y = "Anzahl Messungen",
    fill = "Messstelle"
  ) +
  scale_fill_manual(
    values = c(
      "1" = "#F8766D",
      "2" = "#7CAE00",
      "3" = "#00BFC4",
      "4" = "#C77CFF"
    )
  ) +
  theme(
    axis.title.x = element_text(size = 16),
    axis.title.y = element_text(size = 16),
    
    axis.text.x = element_text(size = 14),
    axis.text.y = element_text(size = 14),
    
    legend.title = element_text(size = 15),
    legend.text = element_text(size = 14),
    
    panel.grid.major = element_line(color = "grey75"),
    panel.grid.minor = element_line(color = "grey85"),
    
    axis.ticks = element_blank(),
    
    panel.background = element_rect(fill = "white", color = NA),
    
    strip.background = element_blank(),
    strip.text = element_blank()
  )
```

```{r}
#ggsave(
#  "Histogramm_Häufigkeit der Wasserstände_Fläche 3 (ohne MS4).png",
#  width = 10,
#  height = 6,
#  dpi = 300
#)
```

## 3.2 Jahresverlauf der Wassertiefe (MT vs MN vs L)

```{r}
# Liniendiagramm - Jahresverlauf
# Zeitlicher Verlauf der mittleren Wassertiefe nach Standort

ggplot(WT_mittel, aes(x = Datum, y = WT_mean, color = Standort)) +
  geom_line(linewidth = 1) +
  #geom_point(size = 2) +
  labs(
    title = "",
    x = "",
    y = "Mittlere Wassertiefe (cm)",
    color = "Fläche"
  ) +
  scale_color_manual(
    breaks = c("MT", "MN", "L"),
    values = c(
      "MT" = "#D55E00",
      "MN" = "#6495ED",
      "L"  = "#006400"
    ),
    labels = c(
      "MT" = "1",
      "MN" = "2",
      "L"  = "3"
    )
  ) +
  theme(
    axis.title.x = element_text(size = 16),
    axis.title.y = element_text(size = 16),

    axis.text.x = element_text(angle = 45, hjust = 1, size = 14),
    axis.text.y = element_text(size = 14),

    legend.title = element_text(size = 15),
    legend.text = element_text(size = 14),

    panel.grid.major = element_line(color = "grey75"),
    panel.grid.minor = element_line(color = "grey85"),

    axis.ticks = element_blank(),

    panel.background = element_rect(fill = "white", color = NA)
  ) +
  scale_x_date(
    date_breaks = "1 month",
    date_labels = "%b %Y"
  )
```

```{r}
#ggsave(
  #"Zeitlicher Verlauf der mittleren Wassertiefe nach Standort.png",
  #width = 10,
  #height = 6,
  #dpi = 300
#)
```

## 3.3 Unterschiede zwischen den Standorten

```{r}
# Boxplot pro Standort, Mittelwert der verschiedenen Messpunkte

ggplot(WT_mittel, aes(x = factor(Standort,levels = c("MT", "MN", "L")), y = WT_mean, fill = Standort)) +
  geom_boxplot() +
  labs(
    title = "",
    x = "Fläche",
    y = "Mittlere Wassertiefe (cm)"
  ) +
  scale_x_discrete(labels = c(
    "MT" = "1",
    "MN" = "2",
    "L"  = "3"
  )) +
  scale_fill_manual(
    values = c(
      "MT" = "#D55E00",
      "MN" = "#6495ED",
      "L"  = "#006400"
    )
  ) +
  theme(
    axis.title.x = element_text(size = 16),
    axis.title.y = element_text(size = 16),

    axis.text.x = element_text(size = 14),
    axis.text.y = element_text(size = 14),

    legend.position = "none",   

    panel.grid.major = element_line(color = "grey75"),
    panel.grid.minor = element_line(color = "grey85"),

    axis.ticks = element_blank(),

    panel.background = element_rect(fill = "white", color = NA)
  )
```

```{r}
#ggsave(
  #"Boxplot_Vergleich der Flächen.png",
  #width = 10,
  #height = 6,
  #dpi = 300
#)
```

```{r}
# Boxplot pro Standort, Messpunkte farblich unterscheiden
# Vergleich der Wassertiefen nach Standort und Messstelle (Mai–Sep 2025)

ggplot(Wassertiefen,
       aes(x = factor(Standort, levels = c("MT", "MN", "L")),
           y = Wassertiefe,
           fill = factor(Messpunkt))) +

  geom_boxplot(position = position_dodge(0.8)) +

  labs(
    title = "",
    x = "Fläche",
    y = "Wassertiefe (cm)",
    fill = "Messstelle"
  ) +

  scale_x_discrete(labels = c(
    "MT" = "1",
    "MN" = "2",
    "L"  = "3"
  )) +

  theme(
    axis.title.x = element_text(size = 16),
    axis.title.y = element_text(size = 16),

    axis.text.x = element_text(size = 14),
    axis.text.y = element_text(size = 14),

    legend.title = element_text(size = 15),
    legend.text = element_text(size = 14),

    panel.grid.major = element_line(color = "grey75"),
    panel.grid.minor = element_line(color = "grey85"),

    axis.ticks = element_blank(),

    panel.background = element_rect(fill = "white", color = NA)
  )
```

```{r}
#ggsave(
  #"Boxplot_Vergleich der Wassertiefen nach Standort und Messstelle.png",
  #width = 10,
  #height = 6,
  #dpi = 300
#)
```

## 3.4 Unterschiede innerhalb eines Standortes

```{r}
#### Jahresverlauf - Liniendiagramm
plot_lin1 <- function(df, st, titel = NULL) {
  
  # Daten nach Standort filtern
  df_sub1 <- df %>% filter(Standort == st)

  ggplot(df_sub1, aes(x = Datum, y = Wassertiefe, color = factor(Messpunkt))) +
    geom_line(linewidth = 1) +
    #geom_point(size = 2) +
    
    labs(
      title = titel,
      x = "",
      y = "Mittlere Wassertiefe (cm)",
      color = "Messstelle"
    ) +
    
    scale_x_date(
      date_breaks = "1 month",
      date_labels = "%b %Y"
    ) +
    scale_color_manual(
  values = c(
    "1" = "#F8766D",
    "2" = "#7CAE00",
    "3" = "#00BFC4",
    "4" = "#C77CFF"
  )
  ) +
    
    theme(
      axis.title.x = element_text(size = 16),
      axis.title.y = element_text(size = 16),

      axis.text.x = element_text(angle = 45, hjust = 1, size = 14),
      axis.text.y = element_text(size = 14),

      legend.title = element_text(size = 15),
      legend.text = element_text(size = 14),

      panel.grid.major = element_line(color = "grey75"),
      panel.grid.minor = element_line(color = "grey85"),

      axis.ticks = element_blank(),

      panel.background = element_rect(fill = "white", color = NA)
    )
}
```

```{r}
#### Unterschiede zw. den Messstellen - Boxplot 
plot_box <- function(df, st, titel=NULL, x_name=NULL) {
  
  # Daten filtern
  df_sub2 <- df %>% filter(Standort == st)
  
  # x-Achsenname setzen, falls NULL
  if (is.null(x_name)) {
    x_name <- "Messpunkt"  # Standard
  }
  
  ggplot(df_sub2, aes(x = factor(Messpunkt), y = Wassertiefe, fill = factor(Messpunkt))) +
    geom_boxplot() +
    labs(
      title = titel,
      x = x_name,           # hier wird der flexible Name verwendet
      y = "Wassertiefe (cm)",
      fill = "Messstelle"
    ) +
    scale_fill_manual(
  values = c(
    "1" = "#F8766D",
    "2" = "#7CAE00",
    "3" = "#00BFC4",
    "4" = "#C77CFF"
  )
  ) +
    theme(
      axis.title.x = element_text(size = 16),
      axis.title.y = element_text(size = 16),

      axis.text.x = element_text(size = 14),
      axis.text.y = element_text(size = 14),

      legend.title = element_text(size = 15),
      legend.text = element_text(size = 14),

      panel.grid.major = element_line(color = "grey75"),
      panel.grid.minor = element_line(color = "grey85"),

      axis.ticks = element_blank(),

      panel.background = element_rect(fill = "white", color = NA)
    )
}

```

### Meusebach trocken

```{r}
plot_lin1(Wassertiefen, "MT", titel="")
ggsave(filename = "Wassertiefen_MT.png", plot = plot_lin1(Wassertiefen, "MT", titel = ""),width = 16, height = 12,units = "cm",dpi = 300)
```

```{r}
# Boxplot
plot_box(Wassertiefen, st="MT",
         titel="",
         x_name="Meusebach trocken")
```

### Meusebach nass

```{r}
# Liniendiagramm
plot_lin1(Wassertiefen, "MN", titel="")
ggsave(filename = "Wassertiefen_MN.png", plot = plot_lin1(Wassertiefen, "MN", titel = ""),width = 16, height = 12,units = "cm",dpi = 300)
```

```{r}
# Boxplot
plot_box(Wassertiefen, st="MN",
         titel="",
         x_name="Meusebach nass")
```

### Lichtenau

```{r}
# Liniendiagramm
plot_lin1(Wassertiefen, "L", titel="")
ggsave(filename = "Wassertiefen_L.png", plot = plot_lin1(Wassertiefen, "L", titel = ""),width = 16, height = 12,units = "cm",dpi = 300)
```

```{r}
# Boxplot
plot_box(Wassertiefen, st="L",
         titel="",
         x_name="Lichtenau")
```
