---
title: "Vegetation-Analysis-clean"
format: html
editor: visual
---

# 1 Packages

```{r}
library(tidyverse)
library(readxl)
library(writexl)
library(vegan)
library(ggplot2)
```

# 2 Daten einlesen und vorbereiten

```{r}
#| label: read data
#| output: true
vegdata <- read.csv("vegdata_final.csv")
str(vegdata)
#spalten anders ordnen
vegdata <- vegdata %>%
  relocate(Transekt, Transektnummer, .after = Name)
str(vegdata)
#entfernen von Arten, die auf der Artenliste waren, aber in keinem der Plots vorkommen
vegdata <- vegdata[, c(
  names(vegdata)[1:5],
  names(vegdata)[6:ncol(vegdata)][
    colSums(vegdata[, 6:ncol(vegdata)], na.rm = TRUE) > 0
  ]
)]
str(vegdata)
```

```{r}
#| label: convert to long format
#| output: false

#Umwandeln zu Long format: 0-Werte bleiben erhalten

rownames(vegdata) <- vegdata$Name 
vegdata$Name <- NULL 
ncol(vegdata) 
str(vegdata)
art_cols <- grep("_(TL|HL|ML|SL)$", names(vegdata), value = TRUE)
veg_long <- vegdata %>%
  rownames_to_column("Name") %>%
  pivot_longer(cols = all_of(art_cols), names_to = "Art_full", values_to = "Deckung") %>% 
  tidyr::separate(Art_full, into = c("Art", "Schicht"), sep = "_(?=[A-Z]{1,2}$)")
#sep trennt die Schicht sauber ab, da Arten als Gattung_Epitheton_Schicht vorliegen
str(veg_long)
```

```{r}
#| label: create subsets

#subsets für jede fläche machen
Lic_subset <- subset(veg_long, site == "Lic")
MN_subset <- subset(veg_long, site =="Meu_nass")
MT_subset <- subset(veg_long, site =="Meu_trock")

```

# 3 Exploration

Top 10 Arten nach Deckung

```{r}
#mittlere Deckungen
p1 <- Lic_subset %>%
  group_by(Art) %>%
  summarise(
    mean_deckung = mean(Deckung, na.rm = TRUE),
    n = sum(Deckung > 0)
  ) %>%
  arrange(desc(mean_deckung)) %>%
  slice_head(n = 10) %>%
  ggplot(aes(x = reorder(Art, mean_deckung), y = mean_deckung)) +
  geom_col(fill = "darkgreen") +
  geom_text(aes(label = paste0("n=", n)),
            hjust = -0.1, size = 3) +
  coord_flip() +
  scale_y_continuous(limits = c(0, 45))+
  labs(
    x = "Art",
    y = "Mittlere Deckung %",
    title = "Kleiner Sumpf"
  ) +
  theme_minimal()

p2 <- MN_subset %>%
  group_by(Art) %>%
  summarise(
    mean_deckung = mean(Deckung, na.rm = TRUE),
    n = sum(Deckung > 0)
  ) %>%
  arrange(desc(mean_deckung)) %>%
  slice_head(n = 10) %>%
  ggplot(aes(x = reorder(Art, mean_deckung), y = mean_deckung)) +
  geom_col(fill = "darkgreen") +
  geom_text(aes(label = paste0("n=", n)),
            hjust = -0.1, size = 3) +
  coord_flip() +
  scale_y_continuous(limits = c(0, 45))+
  labs(
    x = "Art",
    y = "Mittlere Deckung %",
    title = "Auf der Pfalz"
  ) +
  theme_minimal()

p3 <- MT_subset %>%
  group_by(Art) %>%
  summarise(
    mean_deckung = mean(Deckung, na.rm = TRUE),
    n = sum(Deckung > 0)
  ) %>%
  arrange(desc(mean_deckung)) %>%
  slice_head(n = 10) %>%
  ggplot(aes(x = reorder(Art, mean_deckung), y = mean_deckung)) +
  geom_col(fill = "darkgreen") +
  geom_text(aes(label = paste0("n=", n)),
            hjust = -0.1, size = 3) +
  coord_flip() +
  scale_y_continuous(limits = c(0, 45))+
  labs(
    x = "Art",
    y = "Mittlere Deckung %",
    title = "Fuchshügel"
  ) +
  theme_minimal()

#p_all <- (p1/p2/p3)+plot_annotation(
#    title = "Top 10 Arten nach mittlerer Deckung",
#    theme = theme(plot.title = element_text(size = 18, face = "bold", hjust = 0.5)))
#ggsave("top10_deckung.png", p_all,
#       width = 14, height = 6, dpi = 300)
```

Deckung nach Layer

```{r}
layer_deckung <- veg_long %>%
  group_by(site, Schicht) %>%
  summarise(Deckung = mean(Deckung, na.rm = TRUE), .groups = "drop") %>%
  group_by(site) %>%
  mutate(prop = Deckung / sum(Deckung))
str(layer_deckung)

layer_deckung$Schicht <- factor(
  layer_deckung$Schicht,
  levels = c("TL", "SL", "HL", "ML")
)
  
ggplot(layer_deckung, aes(x = site, y = prop, fill = Schicht)) +
  geom_col() +
  labs(y = "Anteil der Deckung", x = NULL) +
  geom_text(aes(label = round(prop,2)), size = 3, position = position_stack(vjust = 0.5))+
  scale_x_discrete(labels = c(
    "Meu_nass" = "Auf der Pfalz",
    "Meu_trock" = "Fuchshügel",
    "Lic" = "Kleiner Sumpf"))+
  theme_minimal()

#ggplot(layer_deckung, aes(fill=Schicht, y=Deckung, x=site)) + 
#    geom_bar(position="fill", stat="identity")
```

# 4 Zeigerwerte einlesen und vorbereiten

```{r}
# Zeigerwerte von GBIF
zeigerwerte <- read.table("dwca-zeigerwerte-v1.2/ellenberg.txt",sep = "\t", header = TRUE)
zeigerwerte <- zeigerwerte %>%
  rename(gbif_name = id)
# Liste meiner Arten, Artnamen für GBIF-Artnamen angepasst
mapping <- read_xlsx("artenliste_mapping.xlsx")

# Tabellen zusammenführen
zeiger_mapped <- zeigerwerte %>%
  inner_join(mapping, by = "gbif_name") %>%
  select(gbif_name, my_name, light, temperature, continental, wetness, alkalinity, nitrogen, salinity)

# Tabelle aufräumen
zeiger_mapped <- zeiger_mapped %>%
  mutate(across(
    c(light, temperature, continental, wetness, alkalinity, nitrogen, salinity),
    ~ str_remove_all(.x, "[~()xX=]") %>%
      as.numeric()
  ))
zeiger_mapped <- zeiger_mapped %>%
  rename(Art = my_name)
zeiger_mapped <- zeiger_mapped %>%
  select(-gbif_name)
```

gewichtete Zeigerwerte berechnen

```{r}
#gewichtete zeigerwerte berechnen
combined_data <- left_join(veg_long, zeiger_mapped, by = "Art")
str(combined_data)

weighted_values <- combined_data %>%
  group_by(plot.ID, Name, site, Transekt, Transektnummer) %>%
  summarise(
    Weighted_light = sum(Deckung * light, na.rm = TRUE) / sum(Deckung, na.rm = TRUE),
    Weighted_temperature = sum(Deckung * temperature, na.rm = TRUE) / sum(Deckung, na.rm = TRUE),
    Weighted_wetness = sum(Deckung * wetness, na.rm = TRUE) / sum(Deckung, na.rm = TRUE),
    Weighted_nitrogen = sum(Deckung * nitrogen, na.rm = TRUE) / sum(Deckung, na.rm = TRUE),
    Weighted_continental = sum(Deckung * continental, na.rm = TRUE) / sum(Deckung, na.rm = TRUE),
    Weighted_alkalinity = sum(Deckung * alkalinity, na.rm = TRUE) / sum(Deckung, na.rm = TRUE),
    Weighted_salinity = sum(Deckung * salinity, na.rm = TRUE) / sum(Deckung, na.rm = TRUE),
    .groups = "drop"
  )

#write_xlsx(weighted_values, "Zeigerwerte_gewichtet.xlsx")
```

Diversitätsmaße berechnen

```{r}
####species richness, Shannon Index, relative Häufigkeit und species evenness bestimmen####

#anlegen einer Vegetationsmatrix
comm_matrix <- veg_long %>%
  group_by(plot.ID, Art) %>%
  summarise(Deckung = sum(Deckung), .groups = "drop") %>%
  tidyr::pivot_wider(
    names_from = Art,
    values_from = Deckung,
    values_fill = 0
  ) %>%
  tibble::column_to_rownames("plot.ID")
str(comm_matrix)

#berechnen von species richness, shannon Index, relativer Häufigkeit und Evenness

species_richness <- specnumber(comm_matrix)
shannon_index <- diversity(comm_matrix, index = "shannon")
relative_freq <- decostand(comm_matrix, method = "total")
species_evenness <- shannon_index / log(specnumber(comm_matrix))

# Ergebnisse in ein Dataframe packen:

results <- data.frame(
  Plot = rownames(comm_matrix),
  Richness = species_richness,
  Shannon = shannon_index,
  Evenness = species_evenness)

print(results)

#als Excel speichern
#write_xlsx(results, "Ergebnisse_species_richness.xlsx")
```

# 6

```{r}
pca <- rda(comm_matrix)
plot(pca)
summary(pca)
#achsen super lang, leiber dca machen

dca <- decorana(comm_matrix)
summary(dca)

cor(weighted_values[, c(
  "Weighted_light",
  "Weighted_wetness",
  "Weighted_temperature",
  "Weighted_nitrogen",
  "Weighted_alkalinity"
)])

fit <- envfit(dca, weighted_values[, c("Weighted_light",
    "Weighted_temperature",
    "Weighted_wetness",
    "Weighted_nitrogen",
    "Weighted_alkalinity")])
fit

plot(dca)
arrows <- as.data.frame(scores(fit, display = "vectors"))
arrows$Variable <- rownames(arrows)

dca_scores <- scores(dca, display = "sites")
dca_df <- as.data.frame(dca_scores)
dca_df$Name <- rownames(dca_df)
dca_df$site <- vegdata$site[match(dca_df$Name, vegdata$plot.ID)]

ggplot(dca_df, aes(DCA1, DCA2, colour = site)) +
  geom_point(size = 2) +

  geom_segment(
    data = arrows,
    aes(
      x = 0, y = 0,
      xend = DCA1 * 2,
      yend = DCA2 * 2
    ),
    inherit.aes = FALSE,
    arrow = arrow(length = unit(0.25, "cm")),
    colour = "black"
  ) +

  geom_text(
    data = arrows,
    aes(
      x = DCA1 * 2,
      y = DCA2 * 2,
      label = Variable
    ),
    inherit.aes = FALSE
  ) +

  theme_minimal()
```

werte mal die dca aus, mach vlt einzelne dcas für jede fläche

was sollte ich sonst noch analysieren? -\> modelle: diversität, deckung TL usw \~ feuchte, licht usw
